# Site settings
title: Jeff's Blog
header-img: img/home-bg.jpg
email: jeffreyxparker@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
<<<<<<< HEAD
url: "localhost:4000"
=======
url: "http://yourdomain.com"
>>>>>>> origin/master
twitter_username: SBootstrap
github_username:  jeffreyxparker
facebook_username:  jeffreyxparker
email_username:  jeffreyxparker@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
