# Site settings
title: Data in the Strata
header-img: img/datas_in_the_strata2.JPG
email: jeffreyxparker@gmail.com
copyright_name: Jeff Parker
description: A blog from Jeff Parker about data science, economics and life
baseurl: ""
url: "jeffreyxparker.github.io"

twitter_username: jeffreyxparker
github_username:  jeffreyxparker
facebook_username:  jeffreyxparker
linkedin_username: jeffreyxparker
email_username:  jeffrey.x.parker@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]